previews:
  generation: manual
services:
  - type: web
    name: raylac-api
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i && pnpm -F api build
    startCommand: NODE_ENV=production pnpm -F api start
    preDeployCommand: pnpm -F db migrate:prod
    autoDeploy: true
    buildFilter:
      paths:
        - packages/api/**/*
        - packages/shared/**/*
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
  - type: worker
    name: raylac-sync
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i
    startCommand: pnpm -F sync start
    preDeployCommand: pnpm -F db migrate:prod
    rootDir: ./
    autoDeploy: true
    buildFilter:
      paths:
        - packages/sync/**/*
        - packages/shared/**/*  
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString

databases:
  - name: raylac
    databaseName: raylac
    region: oregon
    plan: basic-1gb
    previewPlan: basic-256mb
    postgresMajorVersion: 15
