previews:
  generation: automatic
services:
  - type: web
    name: raylac-api
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i --ignore-scripts && pnpm build
    startCommand: NODE_ENV=production pnpm -F api start
    preDeployCommand: pnpm -F db migrate:prod
    autoDeploy: true
    buildFilter:
      paths:
        - packages/api/**/*
        - packages/shared/**/*
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
  - type: worker
    name: raylac-sync
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: pnpm i --ignore-scripts && pnpm build
    startCommand: pnpm -F sync start
    preDeployCommand: pnpm -F db migrate:prod
    rootDir: ./
    autoDeploy: true
    buildFilter:
      paths:
        - packages/sync/**/*
        - packages/shared/**/*  
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
  - type: web
    name: anvil
    plan: standard
    previewPlan: starter
    runtime: docker
    dockerfilePath: ./packages/ci/Dockerfile.foundary
    dockerCommand: anvil --host 0.0.0.0 --base-fee 10000
    region: oregon
    autoDeploy: false
    rootDir: ./
    buildFilter:
      paths:
        - ./packages/ci/Dockerfile.foundary
databases:
  - name: raylac
    databaseName: raylac
    region: oregon
    plan: basic-1gb
    previewPlan: basic-256mb
    postgresMajorVersion: 15
