previews:
  generation: automatic
services:
  - type: web
    name: raylac-api
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: rm -rf ./packages/{app,contracts,scripts,web} && pnpm i --ignore-scripts && pnpm build
    startCommand: NODE_ENV=production pnpm -F api start
    preDeployCommand: pnpm -F db migrate:prod
    autoDeploy: true
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
      - key: ANVIL_RPC_URL
        fromService:
          name: anvil
          type: web
          envVarKey: RENDER_EXTERNAL_URL
  - type: web
    name: raylac-web
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: rm -rf ./packages/{app,contracts,scripts} && pnpm i --ignore-scripts && pnpm build
    startCommand: NODE_ENV=production pnpm -F web start
    autoDeploy: true
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: raylac-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: raylac
    databaseName: raylac
    region: oregon
    plan: basic-1gb
    previewPlan: basic-256mb
    postgresMajorVersion: 15
