previews:
  generation: automatic
services:
  - type: web
    name: raylac-api
    plan: standard
    previewPlan: starter
    runtime: node
    region: oregon
    buildCommand: rm -rf ./packages/{app,scripts,web} && pnpm i --ignore-scripts && pnpm build
    startCommand: NODE_ENV=production pnpm -F api start
    preDeployCommand: pnpm -F db migrate:prod
    autoDeploy: true
    envVars:
      - fromGroup: raylac
      - key: NODE_VERSION
        value: 18.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: raylac
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: raylac-redis
          type: redis
          property: connectionString
      
     # A Redis instance that allows all external connections
  - type: redis
    name: raylac-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere


databases:
  - name: raylac
    databaseName: raylac
    region: oregon
    plan: basic-1gb
    previewPlan: basic-256mb
    postgresMajorVersion: 15
