[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
build_info = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
opt-sepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[dependencies]
forge-std = "1.9.3"
account-abstraction = { version = "0.6.0", git = "https://github.com/eth-infinitism/account-abstraction.git", tag = "v0.6.0" }
"@openzeppelin-contracts" = "4.2.0"
