name: preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - packages/shared/src/**
      - packages/sync/src/**
      - packages/api/src/**
      - packages/app/src/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-preview:
  # if: ${{ COMMIT_MESSAGE=$(git log -1 --pretty=%B) && ! contains(COMMIT_MESSAGE, '[skip build]') }}
    name: Setup EAS preview
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Commit Message
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Print Commit Message
        run: echo ${{ env.COMMIT_MESSAGE }}

      - name: Check if we should skip the build step
        run: if ${{ ! contains(env.COMMIT_MESSAGE, '[skip build]') }}; then exit 0; else exit 1; fi

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i --ignore-scripts --filter .

      - name: Build
        run: pnpm build

      #- name: Create new preview channel
      #  run: eas channel:create ${{ github.event.pull_request.head.ref }}
      #  working-directory: packages/app
      #  continue-on-error: true

      #- name: Link branch to channel
      #  run: eas channel:edit ${{ github.event.pull_request.head.ref }} --branch ${{ github.event.pull_request.head.ref }}
      #  working-directory: packages/app

      - name: Link branch to test channel
        run: eas channel:edit test --branch ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app

      - name: Create a .env file
        run: printf "EXPO_PUBLIC_RPC_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com\nEXPO_PUBLIC_ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}\n" > .env
        working-directory: packages/app

      #- name: Run eas update for the preview branch
      #  uses: expo/expo-github-action/preview@v8
      #  with:
      #    command: eas update --auto --channel ${{ github.event.pull_request.head.ref }}
      #    working-directory: packages/app
      #    env:
      #      EXPO_PUBLIC_RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
      #      EXPO_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Run eas update for the test branch
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel test
          working-directory: packages/app

  test-ios:
    name: Run Maestro tests on ios
    runs-on: ubuntu-latest
    needs: setup-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: packages/app/build/raylac.zip
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            GIT_COMMIT=${{ github.sha }}
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}

  test-android:
    name: Run Maestro tests on android
    runs-on: ubuntu-latest
    needs: setup-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: packages/app/build/raylac.apk
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            GIT_COMMIT=${{ github.sha }}
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}