name: preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - packages/shared/src/**
      - packages/sync/src/**
      - packages/api/src/**
      - packages/app/src/**
  workflow_dispatch:

jobs:
  setup-preview:
    name: Setup EAS preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i

      - name: Create new preview channel
        run: eas channel:create ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app
        continue-on-error: true

      - name: Link branch to channel
        run: eas channel:edit ${{ github.event.pull_request.head.ref }} --branch ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app

      - name: Link branch to test channel
        run: eas channel:edit test --branch ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app

      - name: Run eas update for the preview branch
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel ${{ github.event.pull_request.head.ref }}
          working-directory: packages/app
        env:
          EXPO_PUBLIC_RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
          EXPO_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: Run eas update for the test branch
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel test
          working-directory: packages/app
        env:
          EXPO_PUBLIC_RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
          EXPO_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

  test:
    name: Run Maestro tests on the test channel
    runs-on: ubuntu-latest
    needs: setup-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/raylac.apk
          workspace: packages/app
