name: preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - packages/shared/**
      - packages/shared-backend/**
      - packages/sync/**
      - packages/api/**
      - packages/app/**
      - .github/workflows/preview.yaml
  workflow_dispatch:

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com


jobs:
  setup-preview:
    name: Setup EAS preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: pnpm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Remove unnecessary packages
        run: rm -rf ./packages/{tests,ci,web,scripts}

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Upload sourcemaps
        run: pnpm -F api sentry:sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Create a .env file
        run: printf "EXPO_PUBLIC_RPC_URL=${{ env.RPC_URL }}\nEXPO_PUBLIC_ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}\nAPP_VARIANT=preview" > .env
        working-directory: packages/app

      - name: Run eas update for the staging branch
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch staging
          working-directory: packages/app
        env:
          APP_VARIANT: staging


  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      TEST_ACCOUNT_MNEMONIC: ${{ secrets.TEST_ACCOUNT_MNEMONIC }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: pnpm

      - name: Remove unnecessary packages
        run: rm -rf ./packages/{app,web,scripts}

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint
      - name: Setup test environment
        run: pnpm -F ci run setup

      - name: Get the PR Postgres connection string
        run: |
          PR_DB_CONNECTION_STRING=$(pnpm --silent exec -- pnpm -F ci run print-pr-postgres-connection-string --silent | awk -F'=' '{print $2}' | xargs)
          echo "DATABASE_URL=$PR_DB_CONNECTION_STRING" >> $GITHUB_ENV
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

      - name: Run integration tests
        run: pnpm -F tests test
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          ANVIL_RPC_URL: https://anvil-pr-${{ github.event.pull_request.number }}.onrender.com
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          INDEXER_URL: https://raylac-indexer-pr-${{ github.event.pull_request.number }}.onrender.com
          GIT_COMMIT: ${{ github.event.pull_request.head.sha }}
