name: Integration test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      apiUrl:
        description: 'API URL'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run lint
        run: pnpm turbo lint

      # - name: Run tests
      #   run: pnpm -F tests test
      #   env:
      #    RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
      #    TEST_ACCOUNT_MNEMONIC: ${{ secrets.TEST_ACCOUNT_MNEMONIC }}
      #    ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}