name: Maestro tests
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-preview:
    name: Push updates to the test channel
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Print PR number
        run: echo "${{ github.event.pull_request.number }}"

      - name: Print SHA
        run: echo "${{ github.sha }}"

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Create a PR branch
        run: eas branch:create ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app
        continue-on-error: true

      - name: Link branch to test channel
        run: eas channel:edit test --branch ${{ github.event.pull_request.head.ref }}
        working-directory: packages/app

      - name: Create a .env file
        run: printf "EXPO_PUBLIC_RPC_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com\nEXPO_PUBLIC_ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}\n" > .env
        working-directory: packages/app

      - name: Run eas update for the test branch
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel test
          working-directory: packages/app

  setup-test-env:
    name: Setup test environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Setup test environment
        run: pnpm -F ci run setup
        env:
          RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
          TEST_ACCOUNT_MNEMONIC: ${{ secrets.TEST_ACCOUNT_MNEMONIC }}

  test-ios:
    name: Run Maestro tests on ios
    runs-on: ubuntu-latest
    needs: [setup-preview, setup-test-env]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-binary-id: 019d6dd75a4e12679a04cebfb2c981c7bea211fe
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            GIT_COMMIT=${{ github.sha }}
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}

  test-android:
    name: Run Maestro tests on android
    runs-on: ubuntu-latest
    needs: [setup-preview, setup-test-env]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-binary-id: 93c0d33d4b71a7bd733236bb1e000557f7bc9efd
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            GIT_COMMIT=${{ github.sha }}
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}