name: Integration test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      apiUrl:
        description: 'API URL'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --ignore-scripts

      - name: Run lint
        run: pnpm lint


      # - name: Run tests
      #   run: pnpm -F tests test
      #   env:
      #    RPC_URL: https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
      #    TEST_ACCOUNT_MNEMONIC: ${{ secrets.TEST_ACCOUNT_MNEMONIC }}
      #    ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}