name: Maestro tests
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  # Check if the PR title contains "[ready]" to determine if we should run E2E tests
  check-pr-title:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - name: Check if we should run E2E tests
        id: check
        run: |
          if echo ${{ github.event.pull_request.title }} | grep -q "\[ready\]"; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else 
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  test-ios:
    name: Run Maestro tests on ios
    runs-on: ubuntu-latest
    needs: [check-pr-title]
    if: needs.check-pr-title.outputs.should-run == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-binary-id: 019d6dd75a4e12679a04cebfb2c981c7bea211fe
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}

  test-android:
    name: Run Maestro tests on android
    runs-on: ubuntu-latest
    needs: [check-pr-title]
    if: needs.check-pr-title.outputs.should-run == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Maestro tests on the test channel
        uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-binary-id: 93c0d33d4b71a7bd733236bb1e000557f7bc9efd
          workspace: packages/app/.maestro
          env: |
            API_URL=https://raylac-api-pr-${{ github.event.pull_request.number }}.onrender.com
            TEST_ACCOUNT_MNEMONIC=${{ secrets.TEST_ACCOUNT_MNEMONIC }}
